name: CMakeCI

on:
  push:
    branches: [ testCmake ] # set the trigger and the name of the bracnh
  pull_request:
    branches: [ testCmake ]

jobs:
  build:
    name: testNAmeOfPipeLine
    # use Ubuntu on the runner
    runs-on: ubuntu-18.04
      
    steps:
    - uses: actions/checkout@v2
    - name: arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1.0.2
      with:
        release: '9-2020-q2'
      env:
        #this is a special option because the gcc arm instalation is not correctly.
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    # Install latest CMake.
    - uses: lukka/get-cmake@latest
    - name: "Print some env variables. "
      run: |
       echo "Folder -> $GITHUB_WORKSPACE"
       mkdir "build"
       cd "build"
       cmake ..

    - name: "Make command."
      run: |
       cd "build"
       make
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: all artifacts
        path: |
         ./Debug
         !./Debug/**/*.mk
         !./Debug/**/*.su
        retention-days: 5
    - name: Archive only ELF File
      uses: actions/upload-artifact@v2
      with:
        name: only-ELF-file
        path: ./Debug/**/*.elf
        retention-days: 5
        
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
        name: only-ELF-file
  # configure Matlab tests      
  matlab-test:
    name: Run MATLAB Script
    runs-on: ubuntu-18.04 
        
    steps:
      # becareful! without checkin in a new job the files are not there 
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v1
    - name: Test-case-1-MaxValueis4
      uses: matlab-actions/run-command@v1
      with:
        command: addpath('Matlab'), runTest_maxValis4
    - name: Test-case-2-MaxValueis3
      uses: matlab-actions/run-command@v1
      with:
        command: addpath('Matlab'), runTest_maxValis3

